In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

hcc="../input/hcc-survival-data-set/hcc.csv"
data=pd.read_csv (hcc)
data=data.replace('?',np.NaN)


In [3]:
data=data.astype(float)
print(data.dtypes)

1.Gen            float64
2.Sym            float64
3.Alc            float64
4.HepB           float64
5.HepB           float64
6.HepB           float64
7.HepC           float64
8.Cir            float64
9.End            float64
10.Smo           float64
11.Dia           float64
12.Obe           float64
13.Hem           float64
14.Art           float64
15.CRen          float64
16.HIV           float64
17.Non           float64
18.EVar          float64
19.Spl           float64
20.PHyp          float64
21.Thr           float64
22.LMet          float64
23.Rad           float64
24.Agedia        float64
25.Alcpd         float64
26.cigpy         float64
27.Sta           float64
28.Encdeg        float64
29.Ascdeg        float64
 30.IntNorRat    float64
 31.Alp          float64
 32.Hae          float64
 33.MCorVol      float64
 34.Leu          float64
35.Plat          float64
36.Alb           float64
37.Bil           float64
38.Ala           float64
39.Aspa          float64
40.Gam           float64


In [4]:
data.mean()

1.Gen                 0.806061
2.Sym                 0.639456
3.Alc                 0.739394
4.HepB                0.108108
5.HepB                0.007937
6.HepB                0.269504
7.HepC                0.217949
8.Cir                 0.903030
9.End                 0.079365
10.Smo                0.508065
11.Dia                0.345679
12.Obe                0.129032
13.Hem                0.049296
14.Art                0.364198
15.CRen               0.122699
16.HIV                0.019868
17.Non                0.055944
18.EVar               0.610619
19.Spl                0.560000
20.PHyp               0.714286
21.Thr                0.222222
22.LMet               0.223602
23.Rad                0.680982
24.Agedia            64.690909
25.Alcpd             71.008547
26.cigpy             20.464286
27.Sta                1.018182
28.Encdeg             1.158537
29.Ascdeg             1.441718
 30.IntNorRat         1.421851
 31.Alp           19299.951146
 32.Hae              12.879012
 33.MCor

In [5]:
data=data.drop(['5.HepB','9.End','10.Smo','18.EVar','25.Alcpd','26.cigpy','45.dnod','46.Bil','47.Iro','48.Oxy','49.Fer'],axis=1)
data=data.fillna(value=data.mean())
x=data.drop('Class',axis=1)
y=data['Class']
data

1.Gen     2.Sym  3.Alc    4.HepB    6.HepB    7.HepC  8.Cir  11.Dia  \
0      1.0  0.000000    1.0  0.000000  0.000000  0.000000    1.0     1.0   
1      0.0  0.639456    0.0  0.000000  0.000000  1.000000    1.0     1.0   
2      1.0  0.000000    1.0  1.000000  1.000000  0.000000    1.0     0.0   
3      1.0  1.000000    1.0  0.000000  0.000000  0.000000    1.0     1.0   
4      1.0  1.000000    1.0  1.000000  1.000000  0.000000    1.0     0.0   
..     ...       ...    ...       ...       ...       ...    ...     ...   
160    0.0  0.000000    1.0  0.108108  0.269504  1.000000    1.0     0.0   
161    0.0  1.000000    0.0  0.108108  0.269504  0.217949    1.0     0.0   
162    1.0  0.000000    1.0  0.000000  0.000000  0.000000    1.0     1.0   
163    1.0  0.000000    1.0  1.000000  1.000000  1.000000    1.0     0.0   
164    1.0  1.000000    1.0  0.000000  0.000000  1.000000    1.0     0.0   

       12.Obe  13.Hem  ...    36.Alb     37.Bil      38.Ala     39.Aspa  \
0    0.129032     1.0  ...  3.400000   2.100000   34.000000   41.000000   
1    0.000000     0.0  ...  3.445535   3.087938   67.093168   96.382716   
2    0.000000     0.0  ...  3.300000   0.400000   58.000000   68.000000   
3    0.000000     0.0  ...  3.700000   0.400000   16.000000   64.000000   
4    0.000000     0.0  ...  4.100000   0.700000  147.000000  306.000000   
..        ...     ...  ...       ...        ...         ...         ...   
160  0.000000     0.0  ...  4.600000   0.500000   35.000000   40.000000   
161  0.000000     0.0  ...  3.000000   3.600000   50.000000   91.000000   
162  1.000000     0.0  ...  4.300000   0.600000   53.000000   52.000000   
163  0.000000     0.0  ...  4.800000   1.100000   50.000000   60.000000   
164  0.000000     0.0  ...  2.200000  28.500000   78.000000  127.000000   

         40.Gam      41.Alk   42.Prot   43.Crea  44.NNod  Class  
0    183.000000  150.000000  7.100000  0.700000      1.0    1.0  
1    268.026543  212.211605  8.961039  1.127089      1.0    1.0  
2    202.000000  109.000000  7.000000  2.100000      5.0    1.0  
3     94.000000  174.000000  8.100000  1.110000      2.0    0.0  
4    173.000000  109.000000  6.900000  1.800000      1.0    1.0  
..          ...         ...       ...       ...      ...    ...  
160  449.000000  109.000000  7.600000  0.700000      5.0    1.0  
161  147.000000  280.000000  6.700000  0.700000      1.0    0.0  
162  164.000000  181.000000  7.500000  1.460000      5.0    1.0  
163  320.000000  170.000000  8.400000  0.740000      5.0    0.0  
164  444.000000  462.000000  6.600000  3.950000      5.0    0.0  

[165 rows x 39 columns]

In [6]:
model=DecisionTreeClassifier()
y_pred = cross_val_predict(model,x, y, cv=10)
met = confusion_matrix(y, y_pred)
print(met)

tp=met[0][0]
fp=met[0][1]
fn=met[1][0]
tn=met[1][1]
pr=tp/(tp+fp)
rec=tp/(tp+fn)
f1=2*pr*rec/(pr+rec)
acc=(tp+tn)/(tp+fp+tn+fn)
print("DecisionTree accuracy:",acc)
print("DecisionTree precision:",pr)
print("DecisionTree recall:",rec)
print("DecisionTree f1 score:",f1)


[[29 34]
 [34 68]]
DecisionTree accuracy: 0.5878787878787879
DecisionTree precision: 0.4603174603174603
DecisionTree recall: 0.4603174603174603
DecisionTree f1 score: 0.4603174603174603


In [7]:
model1=RandomForestClassifier()
y1_pred = cross_val_predict(model1,x, y, cv=10)
met = confusion_matrix(y, y1_pred)
print(met)

tp=met[0][0]
fp=met[0][1]
fn=met[1][0]
tn=met[1][1]
pr=tp/(tp+fp)
rec=tp/(tp+fn)
f1=2*pr*rec/(pr+rec)
acc=(tp+tn)/(tp+fp+tn+fn)
print("RFC accuracy:",acc)
print("RFC precision:",pr)
print("RFC recall:",rec)
print("RFC f1 score:",f1)

[[34 29]
 [13 89]]
RFC accuracy: 0.7454545454545455
RFC precision: 0.5396825396825397
RFC recall: 0.723404255319149
RFC f1 score: 0.6181818181818182


In [8]:
model2=GaussianNB()
y2_pred = cross_val_predict(model2,x, y, cv=10)
met = confusion_matrix(y, y2_pred)
print(met)

tp=met[0][0]
fp=met[0][1]
fn=met[1][0]
tn=met[1][1]
pr=tp/(tp+fp)
rec=tp/(tp+fn)
f1=2*pr*rec/(pr+rec)
acc=(tp+tn)/(tp+fp+tn+fn)
print("GNB accuracy:",acc)
print("GNB precision:",pr)
print("GNB recall:",rec)
print("GNB f1 score:",f1)

[[26 37]
 [22 80]]
GNB accuracy: 0.6424242424242425
GNB precision: 0.4126984126984127
GNB recall: 0.5416666666666666
GNB f1 score: 0.46846846846846846


In [9]:
model3=LogisticRegression()
y3_pred = cross_val_predict(model3,x, y, cv=10)
met = confusion_matrix(y, y3_pred)
print(met)

tp=met[0][0]
fp=met[0][1]
fn=met[1][0]
tn=met[1][1]
pr=tp/(tp+fp)
rec=tp/(tp+fn)
f1=2*pr*rec/(pr+rec)
acc=(tp+tn)/(tp+fp+tn+fn)
print("LR accuracy:",acc)
print("LR precision:",pr)
print("LR recall:",rec)
print("LR f1 score:",f1)

AttributeError: 'str' object has no attribute 'decode'

In [10]:
model4=KNeighborsClassifier()
y4_pred = cross_val_predict(model4,x, y, cv=10)
met = confusion_matrix(y, y4_pred)
print(met)

tp=met[0][0]
fp=met[0][1]
fn=met[1][0]
tn=met[1][1]
pr=tp/(tp+fp)
rec=tp/(tp+fn)
f1=2*pr*rec/(pr+rec)
acc=(tp+tn)/(tp+fp+tn+fn)
print("KNN accuracy:",acc)
print("KNN precision:",pr)
print("KNN recall:",rec)
print("KNN f1 score:",f1)

[[19 44]
 [22 80]]
KNN accuracy: 0.6
KNN precision: 0.30158730158730157
KNN recall: 0.4634146341463415
KNN f1 score: 0.36538461538461536


In [11]:
model5=SVC()
y5_pred = cross_val_predict(model5,x, y, cv=10)
met = confusion_matrix(y, y5_pred)
print(met)

tp=met[0][0]
fp=met[0][1]
fn=met[1][0]
tn=met[1][1]
pr=tp/(tp+fp)
rec=tp/(tp+fn)
f1=2*pr*rec/(pr+rec)
acc=(tp+tn)/(tp+fp+tn+fn)
print("SVC accuracy:",acc)
print("SVC precision:",pr)
print("SVC recall:",rec)
print("SVC f1 score:",f1)

[[ 7 56]
 [ 3 99]]
SVC accuracy: 0.6424242424242425
SVC precision: 0.1111111111111111
SVC recall: 0.7
SVC f1 score: 0.19178082191780818


In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve,auc

DTC_fpr,DTC_tpr,threshold=roc_curve(y,y_pred)
logreg_fpr,logreg_tpr,threshold=roc_curve(y,y3_pred)
GNB_fpr,GNB_tpr,threshold=roc_curve(y,y2_pred)
RFC_fpr,RFC_tpr,threshold=roc_curve(y,y1_pred)
KNN_fpr,KNN_tpr,threshold=roc_curve(y,y4_pred)
SVC_fpr,SVC_tpr,threshold=roc_curve(y,y5_pred)

auc0=auc(DTC_fpr,DTC_tpr)
auc1=auc(logreg_fpr,logreg_tpr)
auc2=auc(GNB_fpr,GNB_tpr)
auc3=auc(RFC_fpr,RFC_tpr)
auc4=auc(KNN_fpr,KNN_tpr)
auc5=auc(SVC_fpr,SVC_tpr)

plt.plot(DTC_fpr,DTC_tpr,label='DTC(auc=%0.3f)'%auc0)
plt.plot(logreg_fpr,logreg_tpr,label='LR(auc=%0.3f)'%auc1)
plt.plot(GNB_fpr,GNB_tpr,label='GNB(auc=%0.3f)'%auc2)
plt.plot(RFC_fpr,RFC_tpr,label='RFC(auc=%0.3f)'%auc3)
plt.plot(KNN_fpr,KNN_tpr,label='KNN(auc=%0.3f)'%auc4)
plt.plot(SVC_fpr,SVC_tpr,label='SVC(auc=%0.3f)'%auc5)

xl=np.linspace(0,1,num=10000)
yl=xl
plt.plot(xl,yl,linestyle='-.',lw=2,color='black')

plt.grid(True)
plt.title('ROC(Reciever Operating Characteristic Curve)',name='Courier')
plt.xlabel('False Positive Rate',name='Courier')
plt.ylabel('True Positive Rate',name='Sans')
plt.legend()
plt.show

print(DTC_fpr,DTC_tpr)
print(logreg_fpr,logreg_tpr)
print(GNB_fpr,GNB_tpr)
print(RFC_fpr,RFC_tpr)
print(KNN_fpr,KNN_tpr)
print(SVC_fpr,SVC_tpr)